# Generated by Django 4.2.1 on 2023-05-07 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='datecompleted',
        ),
    ]
